jobs:
  include:
  - stage: Build

    sudo: required
    language: minimal
    services:
    - docker
    script: docker build --build-arg CODECOV_TOKEN --build-arg "APP_VERSION=$(make version)" -t "${DOCKER_USER}/$(make name):$(make version)" .
    after_success:
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - docker push "${DOCKER_USER}/$(make name):$(make version)"

  - stage: Publish

    sudo: required
    language: minimal
    services:
    - docker
    script:
    - curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "docker_promote"
    - echo "${DOCKER_PASS}" | docker login -u "${DOCKER_USER}" --password-stdin
    - scripts/docker_promote "${DOCKER_USER}/$(make name)" "$(make version)"
    after_success:
    - curl -q -sSL --max-time 10 -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/netatmo

  - stage: Deploy

    language: minimal
    script: |
      sed \
        -e "s|\${NETATMO_ACCESS_TOKEN}|${NETATMO_ACCESS_TOKEN}|g" \
        -e "s|\${NETATMO_CLIENT_ID}|${NETATMO_CLIENT_ID}|g" \
        -e "s|\${NETATMO_CLIENT_SECRET}|${NETATMO_CLIENT_SECRET}|g" \
        -e "s|\${NETATMO_REFRESH_TOKEN}|${NETATMO_REFRESH_TOKEN}|g" \
        -e "s|\${NETATMO_SCOPES}|${NETATMO_SCOPES}|g" \
        -e "s|\${BASIC_USERS}|${BASIC_USERS}|g" \
        -e "s|\${BASIC_WORK_USERS}|${BASIC_WORK_USERS}|g" \
        -e "s|\\\$|\$\$|g" \
        docker-compose.yml > docker-compose-env.yml
      curl -q -sSL --max-time 10 "https://raw.githubusercontent.com/ViBiOh/scripts/master/bootstrap" | bash -s "deploy"
      scripts/deploy "$(make name)" "@docker-compose-env.yml"

stages:
  - Build
  - name: Publish
    if: branch = master && type = push
  - name: Deploy
    if: branch = master && type = push

notifications:
  email: false
