apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netatmo
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.94"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: netatmo
    image:
      name: vibioh/netatmo
      tag: "202401060018" # {"$imagepolicy": "default:flux-netatmo-api:tag"}
    config:
      GOMAXPROCS: "1"
      NETATMO_LOGGER_JSON: "true"
      NETATMO_TELEMETRY_URL: datadog.observability:4317
      OTEL_RESOURCE_ATTRIBUTES: env=production,git.repository_url=github.com/ViBiOh/netatmo
      OTEL_SERVICE_NAME: netatmo
    secrets:
      NETATMO_ACCESS_TOKEN: AgAecmqrMMI5uD5tunGruGr5IItbYZ1EAktiudrLRBrhQqN2DT9zWHF5VWXi5FuSIGn4m2IGP40eNngOQX6FjhTj4HkL4ej/7NNzmZkvp6Gg1B50uuHcHF6c3Fi0VH2C5besFmvxdm7jeAAyyxE81wECMZ9fZCbT0m3Os3TvsqQRDa3pQL3nit8F2kuI5mimHgpLU3l0rI9zcsys4Q2TVHTYR3PjOpfctj8rkOTJH4uvuuEIki6dot6JKKOP5szb6HCtewS3v1jxd/HyJlYeCUlGBFb6dmLGyaocnoG26CeTnGjhbUquIFM+HLte/hca9O1MHElyMUr5N0MaV+0trXsIrv3ffpIcSw24TvjCQ8ViXoGYfMClLGPVFWS9exV+MHaEbL+sKj9nFo+IkNz7fHVm0CgtvzgSuskwbkZFny7jhspzSxGtYwYxjzgfR33ll+KFN9FmKXjh15DHk7IOU0YOP7qy28dSUmchHacm515GWrNWygLKAD+2/Q13avSk00tG97ZVAfFVQiMfWdtwYBnjhGQlIs9EarsPUENIPJ1KOGz/OXxRKEvUt2/Vy5xRU6qIxdlJ2TDv6EfOjLj6kUkpCFuDjf/bNFw/wYKaTkJu6QlJWw48Pq9rBuO64ku8jVNXyYyVBrnlVydm6jFNVUnX9eYz184h7dGY5wAyUL97AMii6Qm0s1lfG+ApWKCs9DBb5oYA3ba8DkKvVq4E8ogkCrVgRE6uJZhAvLMRKIVvzY4GjnOve30TUfJNoO95nafzPgo1+gFXDhc=
      NETATMO_CLIENT_ID: AgC9OIAz2rtnSrr8m2WSdw2h9npDa/1t1jiMfLhj1Bzow682hFYRIwWwOgiJ/Qq9CC1Vklah5dkvjX56U9cLeDKdB+ZMGvb9G0bblzYyUMYEFRPbet6IWCbdQ60z1pMiWKuG44u0I8Ba3dswkn2RmV41qAWN5tkt4Y90XF3cOBZTb24K9Pk+O/aJuR7dQU4pSPyWZzqo3bP0GRxASO6DQQIMUknD+dLa82Norx/jC7stpPKfN00/31itYvhLhnEAEc7in4S5adRE+woslQbHewDKlf1jv3zoaoeTPz9XHBNiaFgI/2gMNNKqObeKeZVwbZLK1E/7pOzqH+0EujTrY9MSCQZL/M3xky2r5xagn1ZiKliP90bnqE2C3ae1sst2+kjxtV692uiJd0m7xnhq6sYnW+Hesw5jOnpb4dxF14XmOxtdAPCgeVZo/uWIPGBgoOt+MwGgoA0G1CO5z9780EZfW4nvexTMiJkRmh+aLrZgoRfQ0E7N6ttHe7NfMNUCXkFaRZ0btXmJpPvyo72blWi8j8UfoO45lODWylBn5buHJiiOKGaPdsCF1MHt+QclwraXjkwYwOBk8Qxx05gtFrah5QeyDSjGm1tgV6KXEjcM/PUVASJ0DfeTZJh6IYPaPYYOPMnnSs+iOFueewtVcFU/ZTEyTBycxX+JxxVVwCTNoRUIKBiDwh2ZeAdK1LweDjOiOOhINISa+vtfReJUWVAh4UHcdQh2JGQ=
      NETATMO_CLIENT_SECRET: AgCAx4Qg6J1RGL0zxa9hLvdDQphKTDG8LZJpNLJXz9IiFH2z1cZnTYE8CvAP8X1T5NBwItHfyidTmk+b0Oit0YMXi0WRQ0FSuNomt/TjUoHQH4FKWyi8qovk9DVRdtc5TtoZVNUbYIYXfooziJ9aKYMOWkz+a5l1RuEdxcOC1N3ZKVsZGe9NdwowM2OPV6KJ5AEJuCgMD8PfMv2+STXL18VK5MzR9PkLgi3zzaY1kUQDptslvXsQDaEzjhRJ9wQKgxUKVuqei4KK+obqog1bksNy8I2QYQak6qedcGA59qJBHFOBmuYu8ICefwUABwe6kn3tvG9oXr4VU1rlq24hiOWkpvQ1amfbGI+Ba5knd9vXj55Hyrw+kEaEOJo67vyer+8DCDnaSpSw9ENJg49NuQbRwdZZ2K7fLfSiyde9yeL4RgUp7WmMGBdcJvpTxl+F3WQsjxhaYX2wIXLzHLdYGr/YcFpk7Gr5wYUVg37va5x6zYAx/NGxm0cZZZaZBBiZbrOnV8W9mmhwOwW5OZZwTgGvDgNtLK34HPgRtX131VlC+OD8jy7WLmubYai8cRMniZ7swFtTGUbwnU3GkMCzcxyRyLwKPZYvf9Xgrw+QmmC0N2HYgPT0mqe0SUWwd3TGwRslns6sRkyMx1zf0rgIJp6g8D0CqOrL+Nrt0+V7TEV6Pz/C8bZklHtsU9JsAB1p2w1z6kv/bVLgVyot7+OzAlHUUP0QjeVPHAxiBhN79W3sgzp5iuAIbMd+lA==
      NETATMO_REFRESH_TOKEN: AgAdRnMAeL4pRHs0e0JfAXFwJt9iTCK8o8iP7WmRBJm8/VuzLe8i7eXKOMjPQma2N6b/WWoM/XC0xp4YzVEAv1MGNZY2AYYbr7FX/ypVyq/F+cFOSlBMmfpMHOe7FzvKlx8qRaTAbgVIHzxKaf677TVxNYm3wiKGS7azhjR4dnU0j48GVCsbcpAB9QE8egZ3rtthHB4qPXGN145MWuiWSP2GgM4bRCD9+XXeVUinTEn2s8LVYtjzpL7vKiwp90lEbZMqV54QdGtF2fOSDSZrM/CHJ03IjK1mK04+mgf4m2nbwNkZfOezTopXD9qNYrQmu7xXvB16ZMe2Rhl5yC/mfjPDjHVDHE8CliUKGbhIRBSD9wX7SIc1USyEoNT/YDEAgXCaWlca71mXK4QIRQyZp3J3wgg9jQPMZifWMNs5HmtcDRzHm5Psxj46zyY8oSk02k6Ku3yRQNE6wPzSYW5o+G8RwrMy06oC7x7mOwlxdVoL7b/4a491aDnUakkBx+Sw8FB5ZXxCumH83ZS1AUSBCIFvB1S7r2/mNTrxfG4+U81WvHpkUV3yKia7gcXrFwRuQ82rmDCh9t2gWIxwIZH5zshPmfPAvJGT7+wTSZsgADj3YHoxOTQvH1ef94iaNYa5hHHebiQxL8Dzlrnyhq89h2qqXQ4U+jReCgedLp1mByUBneR1MHDbAjZjOidZU7S63U4WqlE2jgffqul5MAPKLrRS8A9Qn3usynliJrwgFoYTivIeZOkQP9fqxJ29iA/+BpnLMV2W82b8zu0=
      NETATMO_SCOPES: AgA6RHEsf1G9yLMwuSr+AwmFI+QCYN3QNo5vjh65i3M6N40blZTCkrYMRkDJ9whC8IqqafdCITdQy8QyJ8I9KqO+bc0hae1CXbQoYwhtyz2NgnZnWcPL/PsHsYAezxFP/SPJv0Wgg7n/Ezg9N+dpNAH0niEWqXDDz/rNjaRAlTIrFEyzbZjnWtaCleBiX7XfMaTv84hLKdv2L/26MSzoxG6VMypQuq5SbkzwIj8BfH1X0jyxaSaXLsQEEk6x1yqFbKK2HjhsVumBVqvxQZue7aLrvhWQjIrjO1J5eRf8mneNAOaEWc84kS3byrd0xRmAxnSbiTVasoILsnT9aPfhhjGYWj66A3HzUw1ru9gAUrxK6b48zS+w0KJLCUcTZj/MVIxgyVtFJo9CUfpdlxhu5JrSDbIgAypQCipZY5wsjiNzryMu/FUdHzjT8Nqi2Qi63YDLKAlTr9aTd7lEbtdrfWUR6B/zj4G9M70hchoUonFVEtwALxlDM0Er14UKdXrCviGlp2RsKS2ov4ti6m8SZr+NoHTLQOPVyXI8iWxK9+phuvlxZWhAwLojdQzAMborzR3UALliP2QtxeT1YjicDK84xRgEkrJEdLso3gsMVw3DCCXm4CHliBXuFnBxSlhsJFPTD7l54n6dKuvFVtSC/mEipPgSOssG7q/ru/qIKMoVWIjYkdn2k37NldEn7aRGnjw8lZMH3vs0ZQV/Z1YhmiW/vu+GiLafOVQfbd4=
    pprof:
      enabled: true
    service: null
    probes:
      enabled: false
    autoscaling:
      enabled: false
