apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netatmo
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.81"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: netatmo
    image:
      name: vibioh/netatmo
      tag: "202206251601" # {"$imagepolicy": "default:flux-netatmo-api:tag"}
    config:
      NETATMO_LOGGER_JSON: "true"
    secrets:
      NETATMO_ACCESS_TOKEN: AgBEj0DH1jCuXblx+Wkcy+vinqyQD8vKuNtaI+eb//Qf+ibiy1KS3QVSSyYGZVLtfF8hT535GNcWlRa009qTS67plS4S4twqZJnEWkMXWdLd/3RNeTO6sZS3X4JMfT10CQTl9R3GEGCG3A2wGC+Q4qffzTE3FbkM7G/mN3Xy3Sb8hLsimOe4dRV6sTsSyjmhAxvMYQZJsKTEnfnPd8VPETma8V09YVZz3aB9pMw01if8X3bIHwBVKAkDXFv8o1gBylj26RxAEfSEwkTWLRY8C3aXX4qf7iMhRKYjWuqaeyl7Z+hAkvnxugxrIiP57iCcQfR0Cus9un4LVhtbeh7MZoU350AUUkPf5vl+GqiGJ+M4wYNuTKDne91CTuQ/WKQVE17+8u0Lt2RrZWQRbLhRk966ypdKb701lukmWYlK4AU03KCvK1gM4SgoaNeYOi/EIkIOvW/AKZtpwvB0yrthlqAvXhBnJoJy3KdxQKC7VIfqDk+Oxl2lpNsHpmiojTsFc5J0GyN8OgLPClg2oW/sfbnraXJtXRGuOqYRiiybMzTZ8C6UHuo1GLxRt91/uH+7T8csuoS7qyJ6CLjPdv0RwtpEm7AciTo9s7QfmN11ZyPHKMh4LzTN3l6iKIn8rf8sfUCxAwROcuJZQJqozz85nTLFfUncvvhN6d2M/+8y9jbhnOWpcW28sjtlIJTuC4+YdV7rwGyJVYkLfck74n325QXlyzCcqWEFhWb/kvUmtthIEIxsxfQB1L2nhtw5/xs7eziV0AHruWCfnHA=
      NETATMO_CLIENT_ID: AgAOjDiQOrfItrzuhCxCjeD2ylgLDMG/1A5UETgdtNYCFbCK7nySafwjI746f9KLIrvz51/9cKF79ACbHn1WqBmBdooS4yYIejs9t6NMtco7TB2Zsew+ZvNoNTPzmQQvYhHRHEpkP4ZCqaXE2QAweEWHAAN59iHSFg77lrYjBhMw7oQV59V3sStCAMDWSib2rGZWMrILUGg6zP1gsRMdPJf3gX+oPSLu1pZgHrN7liHovce87d2HLma86+OUZ7Anyqh3LpcynJnlOlI2j954V6u/DxOPcm+AGzRdzzdwJYpbTAm2mh96AAzTOvUy/9p647Be7B7m3twB5NWWDZygxiMgrmRA33yzcjIC6IZML0JxoRGUJhDHYYWQx2RcCLZcZTCdrkpX60JNjMxKqQTEr2Tn7VVTN95bQ5KH9iJFL6vZUD0L7Cx8G2sxOfQQujWVKQotqjJPg9ws5WqwjWQMaBi6MdUjCCfNHHkpjXAoDDzPLk6zcyjFaMcw3vPmMTiURGCxCdan0zNSRQHRFhwPVMxHs0boE3z/5nMwyievD/clBe55GShm5wZNmBuOZF7yvQw/2d2gnpSU0h2rrnOjY7YfYCXudlPLPE+2mIPSu273TckQTYcj4K/iugkpzGINz6EO9cYyTnvWUN/I0Pqtnr4BFe5ScfgfjTa4jziPMnuztnv6hdjU/SEV5XrUJ7tczmWnckOqX2lre97tmzkp67YWk214gLyXhmc=
      NETATMO_CLIENT_SECRET: AgCP8RCZAlHpN21yORToq0daparz6a+O3mqmN7fcDBEUHvHWMULbA/h7lRZ3LyDtjcjyJv++c7KtN7qb6DlV60sSfLWjRc5Seq8zfkPACVsxFuYkO3iIUQ57AWqSLyZL4sK7qsRL4kTq+3DZFNUamD2AgWJvjBdWGuqbcszrxcvFhrbVXbPIEwZ1AHH5R2e6rRp9W3nT4D3H1lTCEL5Z7EM5nuPDB5hzZFuVtQOs5ZniW11I8JQkmKFfqKT/RhYs+23ytOMRIFSPUDeEmlzYGsjj/Xk+7dP9jnEfN+kJlpj5+QdqJlGKQa6bwXELzgoSZeV8uzeceS7Xn65zN/wb30n0ao/SosQ7ZEE+wLZfFeu7M9RINngQMF/IOhjIlAFvVkhipaAICFgR47MtApZ68vHhoJu3VG/E4Pqxt1OEVGN9ELcyr0mQUo1zUAKzfkqvGnxg220nXSpxzlMEWDU4NrMMXMYaSNwqgaIN/RSh6NNfoKiZWac7nFsGqfdg3l+VR2YZAwOrbKxaZ1IyyVLc+4AL0UTuoRzZfVc/m/ENky6ztbH1tRABtpK48W2NB0xcGtsyEpS2QjrLX/J5Cax1WSh9k0ewDUalxuMt6MOEyp0QeRiQSqebfnsja0MPc6yGD/gPAbD1G3pnliTS6j2+EEJVW9xZL8SkbR+WZJFDl+qeZ2ZJr2HBGruHO9Jva9/46BatvKEQRPKzW017+xfjH3TU7EF6FxyYreMJJKiW4l/ChvNf+I/th44MnQ==
      NETATMO_REFRESH_TOKEN: AgA1WDpgz7PwplV8vLS8mrDtrMHHX0zfiVIHJrX4WkxMF1I3nSUq/5pMcj2gYXIV9W/oerZQuZ40st3o4Cxf+YNS0K2neXow/cf2tkyqpa/WdHh2/8pX1cTCaQbQ6zCGKKMebcJLOZDFx8JI5TSiFAje/+/AXPgMcSW5Fm7rpnmoe+vZ6QUJSdZA3g2OggUeHM/5bN4ds8J5HjwRl3u1DrROxVWZ/Wh3WXdoJXVKyTzIA5JimTKaR/tGAZQApPHs2N7w0zfpPzeHJjgba6s4TxUKxWKJg4JqlEdT600wU6ysJyJsoXwPR4IGwPB8pwqAuHXgnJOoZN/O6RcmznxodBX8hEHPGDy6IeYWTELAEAF5sW5BuBjio4+nMFnVv7jRDMx6SmiGeGUwMu7uVEybJMDADrPtYXOv7ta4WByIsA3bpmSuBswbxdQsmyH039IGwTwRGRPr4K1dflhpXHyi0Xw21ei09cetTDiWWwuyf/sxil9m5G6suFsuYC0zpDGIxcGfhsbzGzdcI5hxdFjOz76YZl2lfFlfoLj7v1xSDIFI3iD9ENOkRACGEc6F/0p1OcyukFeOgccGEX1QvzN+djguyivvER0XcjDDdyS53Oft/VH/QgvJzwuLG/aig42hIT3DULGRF5OVFmhzDGgdr1uW9P/33m0vNZMVWeEHhp7tsLHHNaGSnooiiWE9IA3z2HHmtTpNkjkQfYxYe6ajU/s/C/ydSYFtJK+HYachb11AKERZz1QpI/sr6uJFhjZ9VZkEVfcoW8oqnks=
      NETATMO_SCOPES: AgANY82ABOw0ecbeexvNes9+vf4UamYUwzzPzF20e082U/0/kolEsqjwJGR9zhe3a0BaIZmBQRzEniZ5/1kdLbpajvAQSxMjO+NNgftzV8dbn3bkV+VvJw+WM4bRSl7S7DBh2UiUkDR5t0Ht0NyZDEY2V63d42KAePXKDD3YsbRIujECRyKmHcyezWi5W5e29k2nor4cT3ZI1JE2kyXTqEr6bii/7q/otZKL3IgY8eUBJnIWyjy6eOdTCxirnlTmtwJ/vQtYlSkGSFSY327Vb5gTtcW225ZHwtHuPPtObfidLXIJyen2PxlZhgUalXscCKI6kg42b/PfhMSdc2b/0R5A7CcsPxlf3lvcjLhrdmHpQvo0+3HP5TNi0XFWda4WfRIkDkQhbaghH0suKZUIVaSW/1G8eCeMUxrJ4TW57Xo2Fz00mPQWGYNQsK8eGu0aCOEvkRsTbBWUM+iI3XCYfY7QkyRNhApAzZtY4ajk9Q8AjR6a+Jk7Ccxq8RcJjRL9is555ynYskIxISy//8PCRm0sm6Sl8RTSOTEjnoayi9+Ajf5KE0GRUn0j+B/HzOcpAQ9KNf2R+7i2JM8XvA0kyRhVYnlLFFLAhSWKjopNy8AODOQWrXPcXikM4UqUnbEfDInmTMIloto8aW/5Q5lI+6SX9wC99q+gjc9inPJPbkfYwjQY3ps6T2eDOkIdTvelCqKIxD4cbLwZJp/jEcm3UepGUDnj1NKH724ZNS8=
    pprof:
      enabled: true
