apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netatmo
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.86"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: netatmo
    image:
      name: vibioh/netatmo
      tag: "202302250122" # {"$imagepolicy": "default:flux-netatmo-api:tag"}
    config:
      NETATMO_LOGGER_JSON: "true"
    secrets:
      NETATMO_ACCESS_TOKEN: AgB2NtkhdPVwgQlr2Fqs1QcsaiXFq+GGglCQcb+3SW9OmWZN1JxArSVzP50MU1YGg7OF5sNLKe+nvniMbjGse0mufLomO8hssiO0swA3Jn5S+HQQFNOfyA767RsvIEF+jMe5235PWFfqGiMRzyTNbWTWp/F3MWuA4GFu0kQLZl1LxAVBvvKwzMZuXTASXOMSUKktq/KhBjolUKLBzP0gxYBdtov/AIHNQW+PNlioNtHpYI27m9xw8vwhhRLTYvEEZByXPznfIPKKLh2x5gaVh+EEs4NspOVLXUGw/eoYEvLAxnxypR+9ChK48dng9bnsWThA1WTSlSkCoJZ6EWv42Ue9HkCmh6rfaaykFuIXPzdb+X0F3sWNlM6Y8sPsfUoIwzeHD7aLXVdqZUUfqc9zltYhk64jp9IdB/AucFcUqMqUL5YSHeHb/Pspb5VZOp8wCoi7fI+OV28wzDDMkGLpkeaRW52NuVA0lFvkTtU2xufCLXiqcA0ZRi3wexz5fXju7C7S2otBqnwu9OEsrQWILNTkVaO1zT6bu873y3oyarCVUJFrYRT33s99UDNDwy5h0DRhVERTsuykdcOfBHceF6FPO4qoZCuWgNnDO0UYLyj2zFYa8AKf6cl8J7TSJUG/NvdzNtdGfQH+LPNgfXDCbRaCZ3qV7rvqlH0xQ2nGnKUJ7xE2ObHJKMbJcl340NrVE/+8oQhBMoPJ38+x6sCwl4ngbMz09X8XKjmbvIgi4gWKeEB5+LdDuN8YXhPTt2LYJznRBQB6n2sXCr8=
      NETATMO_CLIENT_ID: AgC9OIAz2rtnSrr8m2WSdw2h9npDa/1t1jiMfLhj1Bzow682hFYRIwWwOgiJ/Qq9CC1Vklah5dkvjX56U9cLeDKdB+ZMGvb9G0bblzYyUMYEFRPbet6IWCbdQ60z1pMiWKuG44u0I8Ba3dswkn2RmV41qAWN5tkt4Y90XF3cOBZTb24K9Pk+O/aJuR7dQU4pSPyWZzqo3bP0GRxASO6DQQIMUknD+dLa82Norx/jC7stpPKfN00/31itYvhLhnEAEc7in4S5adRE+woslQbHewDKlf1jv3zoaoeTPz9XHBNiaFgI/2gMNNKqObeKeZVwbZLK1E/7pOzqH+0EujTrY9MSCQZL/M3xky2r5xagn1ZiKliP90bnqE2C3ae1sst2+kjxtV692uiJd0m7xnhq6sYnW+Hesw5jOnpb4dxF14XmOxtdAPCgeVZo/uWIPGBgoOt+MwGgoA0G1CO5z9780EZfW4nvexTMiJkRmh+aLrZgoRfQ0E7N6ttHe7NfMNUCXkFaRZ0btXmJpPvyo72blWi8j8UfoO45lODWylBn5buHJiiOKGaPdsCF1MHt+QclwraXjkwYwOBk8Qxx05gtFrah5QeyDSjGm1tgV6KXEjcM/PUVASJ0DfeTZJh6IYPaPYYOPMnnSs+iOFueewtVcFU/ZTEyTBycxX+JxxVVwCTNoRUIKBiDwh2ZeAdK1LweDjOiOOhINISa+vtfReJUWVAh4UHcdQh2JGQ=
      NETATMO_CLIENT_SECRET: AgCAx4Qg6J1RGL0zxa9hLvdDQphKTDG8LZJpNLJXz9IiFH2z1cZnTYE8CvAP8X1T5NBwItHfyidTmk+b0Oit0YMXi0WRQ0FSuNomt/TjUoHQH4FKWyi8qovk9DVRdtc5TtoZVNUbYIYXfooziJ9aKYMOWkz+a5l1RuEdxcOC1N3ZKVsZGe9NdwowM2OPV6KJ5AEJuCgMD8PfMv2+STXL18VK5MzR9PkLgi3zzaY1kUQDptslvXsQDaEzjhRJ9wQKgxUKVuqei4KK+obqog1bksNy8I2QYQak6qedcGA59qJBHFOBmuYu8ICefwUABwe6kn3tvG9oXr4VU1rlq24hiOWkpvQ1amfbGI+Ba5knd9vXj55Hyrw+kEaEOJo67vyer+8DCDnaSpSw9ENJg49NuQbRwdZZ2K7fLfSiyde9yeL4RgUp7WmMGBdcJvpTxl+F3WQsjxhaYX2wIXLzHLdYGr/YcFpk7Gr5wYUVg37va5x6zYAx/NGxm0cZZZaZBBiZbrOnV8W9mmhwOwW5OZZwTgGvDgNtLK34HPgRtX131VlC+OD8jy7WLmubYai8cRMniZ7swFtTGUbwnU3GkMCzcxyRyLwKPZYvf9Xgrw+QmmC0N2HYgPT0mqe0SUWwd3TGwRslns6sRkyMx1zf0rgIJp6g8D0CqOrL+Nrt0+V7TEV6Pz/C8bZklHtsU9JsAB1p2w1z6kv/bVLgVyot7+OzAlHUUP0QjeVPHAxiBhN79W3sgzp5iuAIbMd+lA==
      NETATMO_REFRESH_TOKEN: AgB1sGM0tYFeqtIGClRbWTcJRi5ONEuBO82UYx4Wh5DR5YAHwHWxVGHK7se6bZfTyzd1Qa6Ea3OfkOS26aox32dXigFMbOeELEKGatmSDR9AI9w+VyNc9tBF1QVCd0TjcFjnOC8+tcCK6Lyr9B18Qz94SNwSPbisqd/rP31NwLS5YKz7sNsH9YAs4L6XQiOLoaYaE9lAg5GScMQYpbx36HTVKv0lEmWNLrn/5geR3ddVk4ZTvwQt7L9C+oEFfp0jtPzACYr+bgzLfItvi/yKPDwLrdOhzEvXocuFvBlfUDtH8m7PokuJhk4tT/Vgg/I0tc8/6U5KFZ26fM9aKuAXK7bCFqRm5r7BHlSetlNl8yyO26x6Pw+Kg73YQAliXXZwMRwHxtpA9ll9HcAiGacIhtcbEv8QadIKAX3y0/UFhdvGjZ2HSIVjiy1purqDD4DPBLpWTdCglxD+vIa12awxlQhoivKL10rU0AfAP2XndEDvY39TIMLjaFMKzBRDr1jr9WMt/H0lZOlPzFQhdLbYqy6IkXCn2dlzO9e2IsCgL1OwmJeYM1+E38tPSitI0aJz84809sStxgwF9XnmHhK8yv3ltM/YC2W5ST7LJcOvj2D7VI8pNROiGB0EOO1OfKMIpUcbrBvjLCDJRATVyPCBr00f68UKAWwBQGCGGoTH5yam3JQ0lG3Gf5uP4joA3OMFyiAHMRUri2BCIHX0ZviQ3kwPzBcrYOej/tl3kOMBY852p7+pWSujD6j+48uLpu7X4HB2Vcebhy7V3mM=
      NETATMO_SCOPES: AgA6RHEsf1G9yLMwuSr+AwmFI+QCYN3QNo5vjh65i3M6N40blZTCkrYMRkDJ9whC8IqqafdCITdQy8QyJ8I9KqO+bc0hae1CXbQoYwhtyz2NgnZnWcPL/PsHsYAezxFP/SPJv0Wgg7n/Ezg9N+dpNAH0niEWqXDDz/rNjaRAlTIrFEyzbZjnWtaCleBiX7XfMaTv84hLKdv2L/26MSzoxG6VMypQuq5SbkzwIj8BfH1X0jyxaSaXLsQEEk6x1yqFbKK2HjhsVumBVqvxQZue7aLrvhWQjIrjO1J5eRf8mneNAOaEWc84kS3byrd0xRmAxnSbiTVasoILsnT9aPfhhjGYWj66A3HzUw1ru9gAUrxK6b48zS+w0KJLCUcTZj/MVIxgyVtFJo9CUfpdlxhu5JrSDbIgAypQCipZY5wsjiNzryMu/FUdHzjT8Nqi2Qi63YDLKAlTr9aTd7lEbtdrfWUR6B/zj4G9M70hchoUonFVEtwALxlDM0Er14UKdXrCviGlp2RsKS2ov4ti6m8SZr+NoHTLQOPVyXI8iWxK9+phuvlxZWhAwLojdQzAMborzR3UALliP2QtxeT1YjicDK84xRgEkrJEdLso3gsMVw3DCCXm4CHliBXuFnBxSlhsJFPTD7l54n6dKuvFVtSC/mEipPgSOssG7q/ru/qIKMoVWIjYkdn2k37NldEn7aRGnjw8lZMH3vs0ZQV/Z1YhmiW/vu+GiLafOVQfbd4=
    pprof:
      enabled: true
    service: null
