apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netatmo
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: netatmo
    image:
      name: vibioh/netatmo
      tag: "202207160750" # {"$imagepolicy": "default:flux-netatmo-api:tag"}
    config:
      NETATMO_LOGGER_JSON: "true"
    secrets:
      NETATMO_ACCESS_TOKEN: AgApvdld7IA2f0+pIg6Mmsc+NGYFGkcYlUSx1WlMM5xiUCVL1fDa/TloF8YLlMEu562CUoxMtISpWFeer3k2m1qmXkLdXH1+aEmg7P/TmDJtw+Ap8w7Jzz4kSOPdp/qZKnZhX6MpwbSHnQmwq9PEloMYKPxS+zk6YEDTXUY3T8+L2K+lBu0m+p/v51PNeFUv5qy7RlsVfxn8KTnB5ZRVTjyCfwnLUuFs2G6oc5n7AN7ooOPlHDnYq4nABhcG3SMERJrqSBev/wdhRtjVy7a0AjzI9kMZxS7kft8Pd7xBPcwmzFZr36X3qlPcaoN2x+jhCcE4lZ9l/a4GEbveDWdlb2DzjAQQKDmhWVRgDdnHvY0YztRlyy8+R4inFS/RK6CcuzTDEcsZc9o17ove+Yz190cfcmaekDg9RZgwErNLhVhC7yM1x05u+quRqrMSg8ZXHGJV0JhgeuAOvj8BJMUVQcqjkV4WIeEdh2JiRwmybsWy4CZia1a6gqIAiz7mBVptlrVWtls48OE/ssf9/kw7/9XtS+lrfmEpmqVKfoE3ZTm1V+m2TaHadKe5uS0JiohLCDKnkAO2AKxlS1QqabXzt5xHZs27klZYFruVDauiede9gzvndjTcuCi5gAN+MM7h0XY+vWonU0TDTQ0ygkrA9P9nWTt6YkfppkXUEeGknLiVtkmvDt5pn5O1X+52BQgI6ONiQIHCVDxp0P0EbGiycakisPWQ+Y28rFalxWwjBVH07b/WSul6GuKgYjZhMbEccj7br9KFxt/DJQs=
      NETATMO_CLIENT_ID: AgBHNcWBphPSmwbrDlsegjw3S8mz5fP5Ei0I10m7HPG/mqrK5ZhlhLSFlm/CqbG/xrLaoZkYM/HY2tyGE+7oz7pacfA9QxI2Pdo/niDZOxTGW+VQqCtDX4LOSefWWIo5A58jrIp2GRWalqP/Wipt/4vr6ab9AwrgMXR2FPRa/MZXl+FMF+BVm85u9LxNirr0bI24k7pvk6ALr2CPkoeS6W+hxXhgY2IAAEwmHe2/jU2dH/kUlKo2YI9p1XkFqhEk5w7u8946kYYMSAEOHvJvf6T+GG8T4L5UH3Oo308PilpQ7VN4AsIDX4T/aCk8N4QyI2iwC4kt9BmIba0+suk3NfO4TWOU7o2ZQ1bXq4gqfTvAPI5BrBStNaB+U7J+0OR7UMN5T4LsKFDXYisFf5MeUQTOMKd0Lu0QgJlXdGMrTCCJPGDmF54ezARDGu57X+XzKQ0j5IS80+lYPWDsjUWYtcGELVm+lqRgPkgXAFRBB1ioD6MZnuzl6cg0mQ6iEZdGfMGqhlVSpK2HKpZPqi5ThaDsrmCFElvhLCqNuaEsmtn5+ltvq7RQ0/1nDHMhM+4xq3Ip9Dm1cfzdpq9l3SKyJ5PS583bbvonBJq1Sps9sZOaLylxEQ9O/LkfjvkjTUTRJGp3duI+CRo8O7AFKPhQwsITTBo7jhNuVmayljI2vJDHvJL2z1uTL4+c1Ygnp5Httv/6yYPJF0msmOHyvQsKLLq5gidfSaQfsf4=
      NETATMO_CLIENT_SECRET: AgCfI+z3NOMHtLvO6RgHJGjaVFrAt8HjunNZdSsY9BeV/d+aQvowCMf4EWPWSikOygtWGhc1F+5u4+0Qpw6ywjvAZXMG8bUyn82+0vOzh3F1WtpdCVNwyK4rbe0OAxAsEGtd1lvOHy+YizF8sys3vqBOm95pQw7omXheTcpAB/gk8WhqB8SAhKAwCynSPdxdBWFltTH525wn+y/uXvovjob5DgN6l/C1De0mlkKZVU9zPrw2Tryjk7N1bvTfBTvWdPEQ2sbzIuA/atqQRx7YgqOhejVS2C48hoplKlJlILGx4pFbJKfQs9FJU9fVwQ+u31iO54BBQgYn2XgAvJoQwuUhdX0SwHp3gro+5gUjnu3/x7oEwALterf0NXz9NW/OW87hQzCzaq/zBV/WQjf44jEgHRuv4f+JcApICvVvNAQgzk+PDy+By59sGUh+C3+WRYNDWCaapDla424RU6Xfe5ufFqrIzinS6MRMjvQvD+BOkCH45brnc51tjxtEOizHQShpkdupuvv/df1XFAOgy9wq2NQ1rqPWA/6UASj4330oCi15VHm7wL6G36SRre9bOxCrWmV9r+8cK88oj6plIcjcpKB7v0F8rTnjZW/w2FTiZ5VJ5i1bvoL+CqMtdFVO6QeHZenFAx6YRBogMRHbG0zWnXGX0gbJf4QcAqJT7e8wLEHQyJYvjHXxepZdrYsw2yYp32U/cDL4hh16NhNL/9uKhdfs95+V1KUHSflV9RudcFAzT8XvIFJVjg==
      NETATMO_REFRESH_TOKEN: AgBp0tumlBMhgFR1+LTcDOq949mB/j3KW49q2EoGrc+OR6hX1OI0Lp34u6kHOImMY9VBR6Ymh5m28GvAEVW6TK5HJSkOT5Bd2LYxVbYOlZhFNH8Co2mh/jbElm+lVP3e73qRnsaBI8P8CqutkJebcUcPI2DGjtRiYFBYI58hu4BGQbaYhoLimuG4HQXzG0cmrZLOX8euB9YEZXZz8kYi55hzzAVQrCzyP7/0LoDGGhyLVdBzYMrbzfYveN9xerA0O85zZ8kvA6QNTvjUkvOmtfmsFt1P2ME95rbZ49C2M7VlfuXPXzEhko1pUdE+rVKETVwxY5Mbg79C0ZfRFbZ96thWL4LYxkM49ezZY9nkvPcq+7+mO/buLX75YH6AxasoGkHixPmtViOXpUF4BX9Yhd7oYl3htxAUvyI/oW18XAk6QdkSB/N00WqLvhpAoh28GfFCognvZVTpeNsSzlCjGrB0hNKEb/iwlSRXdYGd9Px+tJOBxmonZv0esWf7EZVMgyIOeT7XELLBUL2RCIsBgCWeF051uIWXMpewGzmZAKobtbVjCUXj+e55UHEqZ9fmNTOa/18PG9s7K5K0PHnrDCGsoXtBhBnRXW/bLyZUkZUT/3XNG6VWv/gzYDdb65Iy/evGvWGo26Uzi/rmps2+vpX3T62uRh0llWnFRcRnA8YInXL/NnRzkSVqhuYmxJKMUnDKj4GEa7CxvODGyn2qd+8XixC6fR1k//O38sC0K0iQP+gTUYel4rMUP+gNwND3uOEc1REUqLxPkTM=
      NETATMO_SCOPES: AgBftAIS/G05N6EZn63CNoN2SNech6D63cKREzCH2pGUKhZBnQk8PJZxR0U+iDXHxhCxwNdhEwkdAOKTg3AUxG5RYn5zEADTHfbWBnLdVLL5Qy/3HLr5PM92kCZmGrrL0snJC+8kPxHsBpxX3AuV7EDihG2vIAcGvRv4h86BdwDbO4rpuyual67QJn+K8w6q8YF86l76F8peocFuI4Gju1Z+rrIhpqUP2XcvDQPcB7dTqDvjYFa8hgS73uPaB/s0kGqfYO8LHiAtNOcYPxUhucp4T+VeIUJvqYXabH0Xa67an7pCgc5bG4E7NGQ/1+Kg8J+uEqzpaaMvAmeToiAlucVE6KcgPny51tydwHk+3uQnjQJkOHzCLFEhmS7h3yIs8JbUYPLyvFQRnzJN8qW1Wlang26rX3LBSDyQeksp2Mg6CIRxSFHym/MDv4ZPQYnjqrcxYquCmyLMpFFeMRFTkrRJHpe/Jzfx9nHMX27HZsu19vEz/lOlcLewg5H/6xIK0aU8+kHGCwh5NGsYrwTXERVdFHIDlhoR4u0v/AmsbGVVuavS6ZoRGlDoseSFRdJ2xIjZ5p8SoPQ81nm3WzwvHn37JsoMriVhw7XNMrrYb/+M6/B7Rl20Uv5awCQqdKga4Xg/8E3yWqFzzRD1t9unH0q59q0QH7mBigyxm7FKL5qUxIGpQQPWWzMqLHEBVhY8txjdk2HZJ1BZoRUXqVQhhMYDlPY4RkeqGJPW/P0=
    pprof:
      enabled: true
    service: null
