openapi: 3.0.0
info:
  description: Golang Web API Template
  title: API Template
  version: '1.0.0'

paths:
  /health:
    get:
      description: Healthcheck of app
      responses:
        '204':
          description: Everything is fine
        '503':
          description: App is shutting down

  /version:
    get:
      description: Version of app

      responses:
        '200':
          description: Version of app
          content:
            text/plain:
              schema:
                type: string

  /metrics:
    get:
      description: Prometheus metrics
      responses:
        '200':
          description: Greeting message
          content:
            text/plain:
              schema:
                type: string

  /devices:
    get:
      description: Netatmo devices
      responses:
        '200':
          description: Devices data
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    $ref: '#/components/schemas/Devices'

components:
  schemas:
    DashboardData:
      type: object
      properties:
        temperature:
          type: number
          format: float
          description: Temperature in celcius
        humidity:
          type: number
          format: float
          description: Humidity in percentage
        noise:
          type: number
          format: float
          description: Noise in dB
        co2:
          type: number
          format: float
          description: CO2 in ppm

    Device:
      type: object
      properties:
        station_name:
          type: string
          description: Station name
        dashboard_data:
          description: Station data
          $ref: '#/components/schemas/DashboardData'
        modules:
          type: array
          description: Additional modules
          items:
            type: object
            properties:
              module_name:
                type: string
                description: Module name
              dashboard_data:
                description: Station data
                $ref: '#/components/schemas/DashboardData'

    Devices:
      type: array
      items:
        $ref: '#/components/schemas/Device'
