openapi: 3.0.0
info:
  description: Golang Web API Template
  title: API Template
  version: '1.0.0'

paths:
  /health:
    get:
      description: Healthcheck of app
      responses:
        '204':
          description: Everything is fine
        '503':
          description: App is shutting down

  /version:
    get:
      description: Version of app

      responses:
        '200':
          description: Version of app
          content:
            text/plain:
              schema:
                type: string

  /metrics:
    get:
      description: Prometheus metrics
      responses:
        '200':
          description: Greeting message
          content:
            text/plain:
              schema:
                type: string
